@baseUrl = http://localhost:3001/api
@userId =

### ERROR TEST
### POST create user 'admin'
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "Password123!",
  "roles": ["admin"],
  "pokemonIds": []
}

### POST create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Player",
  "email": "player@example.com",
  "password": "Password123!",
  "pokemonIds": []
}

### POST login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "player@example.com",
  "password": "Password123!"
}

### POST refresh access token
POST {{baseUrl}}/auth/refresh


### POST logout
POST {{baseUrl}}/auth/logout

### GET all users - admin only
GET {{baseUrl}}/users

### GET user by id
GET {{baseUrl}}/users/{{userId}}


### PATCH update user
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Player I",
  "pokemonIds": [1, 4, 7]
}

### DELETE user - soft/hard delete depending on controller
DELETE {{baseUrl}}/users/{{userId}}
